Enemy Spawner
ChainSafe/BlockBlasterz pull request #38
Opened 2024-02-06 11:53 UTC by rob1997

2024-02-06 11:59 UTC, kantagara commented on Assets/Scripts/NPC/Enemies/EnemySpawner.cs
> +        [SerializeField] private EnemyController enemyPrefab;
I'd make this an array. We'll maybe have more than one enemies.

2024-02-06 11:59 UTC, kantagara commented on Assets/Scripts/NPC/Enemies/EnemySpawner.cs
> +        private ObjectPool<EnemyController> _pool;
OMG UNITYS OBJECT POOL!!!

2024-02-06 12:01 UTC, kantagara approved these changes
Aweomse!

2024-02-06 12:01 UTC, kantagara commented on Assets/Scripts/NPC/Enemies/EnemySpawner.cs
> +        [SerializeField] private EnemyController enemyPrefab;
Ahh but yeah makes sense that each enemy type has it's own spawner, nvm.

2024-02-06 12:17 UTC, sneakzttv approved these changes
yeet object pooling, amazing, never seen it in use before, great way to optimize https://learn.unity.com/tutorial/introduction-to-object-pooling#5ff8d015edbc2a002063971c

2024-02-07 17:12 UTC, oleksandrchainsafe commented on Assets/Scripts/NPC/Enemies/EnemySpawner.cs
> +        private ObjectPool<EnemyController> _pool;
😱🤯

2024-02-07 17:25 UTC, oleksandrchainsafe requested changes
All looks good 👍
Built-in pool - very cool 🔥

The only thing I don't like is Damageable->NpcController->EnemyController mega-hierarchy.

Healthy way would be to split Enemy into a set of components. Each component is responsible for it's own thing (health for example handles damage and sends 'Dead' event when health <= 0). The composition of the components makes gameobject into an enemy, that can walk, take damage, shoot player and so on. Another enemy can do all of that + explode on death because it has one more component that makes him spawn explosion on death.

2024-02-07 17:25 UTC, oleksandrchainsafe commented on Assets/Scripts/NPC/NPCController.cs
> +    public class NPCController : Damageable.Damageable
NpcController, because NPC is more than 2 symbols.

2024-02-08 08:07 UTC, rob1997 commented on Assets/Scripts/NPC/NPCController.cs
> +    public class NPCController : Damageable.Damageable
Yep makes sense, I've made the changes

2024-02-08 11:01 UTC, oleksandrchainsafe approved these changes

2024-02-08 11:02 UTC, merged