Session Manager, Enemy Waves, Loot Drops
ChainSafe/BlockBlasterz pull request #55
Opened 2024-02-20 10:29 UTC by rob1997

2024-02-20 11:03 UTC, kantagara commented on Assets/Scripts/Session/SessionManager.cs
> +                        DirectorController = FindObjectOfType<DirectorController>();
Couldn't these be singletons, since they're controllers?

2024-02-20 11:04 UTC, kantagara approved these changes
Looks good, small comment left but overall, cool!

2024-02-20 13:42 UTC, oleksandrchainsafe commented on Assets/Scripts/Session/SessionManager.cs
> +    public enum SessionState
All the other stuff like loading level, etc.. are parts of the metagame, and in our case can be handled by simply changing scenes.

2024-02-21 10:35 UTC, rob1997 commented on Assets/Scripts/Session/SessionManager.cs
> +                        DirectorController = FindObjectOfType<DirectorController>();
done

2024-02-21 10:49 UTC, kantagara commented on Assets/Prefabs/Weapons/MediumHealthPIckup.prefab
> +  m_TagString: Ammo
Shouldn't this have a Pickup tag instead of Ammo, Ammo shouldn't be a tag at all imo.

2024-02-21 10:52 UTC, rob1997 commented on Assets/Prefabs/Weapons/MediumHealthPIckup.prefab
> +  m_TagString: Ammo
yeah I didn't add it, I duplicated ammo pickup to start that's why it's there

2024-02-21 10:53 UTC, rob1997 commented on Assets/Scripts/Challenges/Reward/EnemyDestroyedReward.cs
> +    public class EnemyDestroyedReward : Reward
I thought maybe we could add item pickups here, plus we would probably reward different scored for destroying different enemies, right?

2024-02-21 11:03 UTC, rob1997 commented on Assets/Prefabs/Weapons/MediumHealthPIckup.prefab
> +  m_TagString: Ammo
changed tag to 'untagged'

2024-02-21 11:04 UTC, kantagara commented on Assets/Scripts/Challenges/Reward/EnemyDestroyedReward.cs
> +    public class EnemyDestroyedReward : Reward
Yeah but this is a reward on when the _challenge_ is completed, not when the Enemy Dies (I think 😁 )

2024-02-21 13:59 UTC, oleksandrchainsafe commented on Assets/Scripts/Challenges/ChallengeManager.cs
> +        protected override bool ShouldNotDestroyedOnLoad => false;
mb ShouldNot**Be**DestroyedOnLoad? or NoDestroyOnLoad?

2024-02-21 14:32 UTC, oleksandrchainsafe requested changes

2024-02-21 14:32 UTC, oleksandrchainsafe commented on Assets/Scripts/Session/SessionController.cs
> +            // TryAddSessionState<LobbyState>();
Can't find the actual states

2024-02-21 14:32 UTC, oleksandrchainsafe commented on Assets/Scripts/Session/DirectorController.cs
> +            waves[_index].BeginWave();
This should be triggered by a session state.

2024-02-21 14:32 UTC, oleksandrchainsafe commented on Assets/Scripts/Session/Wave.cs
> +                DirectorController.Instance.NextWave();
Great overall, but again we should give the responsibility of controlling when each wave starts to the session manager. So basically SessionManager instructs the Director to start spawning fellas and watches (or listens) the current wave to end through the Director's interface.

To better illustrate what I mean imagine 3 states:

- ChilingState: Nothing spawns; when the player triggers the new wave, transitions to FarmingState.
- FarmingState: When enabled tells Director to start wave N; watches wave complete -> ChilingState; watches player die -> GameOverState (same might be true for ChilingState in case there is a static damage dealer on the map)
- GameOverState: triggers GameOverUI to show, saves results/stats/best score.

Dependencies can look something like this: SessionManager->Director->Wave. So SessionManager knows nothing about waves except for some basic info like wave number. Director knows nothing of SessionManager, but provides an interface to start/stop a wave with a certain number and to listen for the current wave completed. Wave knows nothing about both of them.
_Basically it's good when a component like director can be moved to another scene where there is no SessionManager and the game wouldn't break._

2024-02-22 12:07 UTC, sneakzttv approved these changes

2024-02-26 07:15 UTC, rob1997 commented on Assets/Scripts/Challenges/Reward/EnemyDestroyedReward.cs
> +    public class EnemyDestroyedReward : Reward
removed this reward

2024-02-26 07:15 UTC, rob1997 commented on Assets/Scripts/Challenges/ChallengeManager.cs
> +        protected override bool ShouldNotDestroyedOnLoad => false;
changed to `NoDestroyOnLoad`

2024-02-26 07:16 UTC, rob1997 commented on Assets/Scripts/Session/SessionController.cs
> +            // TryAddSessionState<LobbyState>();
Chilling, farming, paused and game over states implemented

2024-02-26 07:16 UTC, rob1997 commented on Assets/Scripts/Session/DirectorController.cs
> +            waves[_index].BeginWave();
it's not being triggered by farming state

2024-02-26 16:46 UTC, oleksandrchainsafe requested changes
All good. The only concern is the state change in GameOverState.

2024-02-26 16:46 UTC, oleksandrchainsafe commented on Assets/Scripts/Session/GameOverState.cs
> +            SessionController.Instance.TryChangeSessionState<GameOverState>();
This part is a bit counterintuitive. I would move this to the Farming & Chilling states.
The problem is that when you read the code, you'd look into the current active state to understand the behavior. With this one the state change happens "out of nowhere", the one debugging this is going to spend some time looking for the reason why the state was changed even though there is no such logic in the current state.

2024-02-27 12:32 UTC, oleksandrchainsafe approved these changes

2024-02-27 15:23 UTC, merged