Dashroll implementation
ChainSafe/BlockBlasterz pull request #6
Opened 2023-11-30 15:57 UTC by RyRy79261

2023-12-01 11:21 UTC, RyRy79261 commented on Assets/Scripts/Player/PlayerController.cs
> +        if (Input.GetKey(KeyCode.S))
@kantagara Yeah our system looks extremely different to the tutorials I was following. Is the new system added yet?

2023-12-01 11:54 UTC, sneakzttv commented on Assets/Scripts/Player/PlayerController.cs
> +        if (Input.GetKey(KeyCode.S))
not yet, this is fine tbh i can alter the input later.

2023-12-01 11:56 UTC, sneakzttv approved these changes

2023-12-01 12:05 UTC, sneakzttv commented on Assets/Scripts/Player/PlayerController.cs
> +        if (Input.GetKey(KeyCode.S))
![image](https://github.com/ChainSafe/BlockBlasterz/assets/57473220/7d89785b-3d74-4073-9659-60f57cbe5b38)

2023-12-01 12:40 UTC, RyRy79261 commented on Assets/Scripts/Player/PlayerController.cs
> +        if (Input.GetKey(KeyCode.S))
Like preferably, isDodgeRolling would be an enum of either left, right, back, forward, idle. That's set in the event triggered by the dashbutton, and in said event determines if theres a specific direction other than default forward and sets it

2023-12-01 12:54 UTC, sneakzttv commented on Assets/Scripts/Player/PlayerController.cs
> +        if (Input.GetKey(KeyCode.S))
fixed will leave reviews :D

2023-12-01 12:58 UTC, RyRy79261 commented on Assets/Scripts/Player/PlayerController.cs
> +        isDodgeRolling = false;
```suggestion
        isDodgeRolling = false;
        // Grapes 
```

2023-12-01 13:01 UTC, sneakzttv commented on Assets/Scripts/Player/PlayerController.cs
>      {
```suggestion
    /// <summary>
    /// Handle player movement
    /// </summary>
    private void Move()
    {
        controller.Move(transform.rotation * currentMovement * moveSpeed * Time.deltaTime);
        
        if (isMovementPressed)
        {
            // animations for later go here following this syntax
            //animator.SetBool("isRunning", true);
        }
        else
        {
            //animator.SetBool("isRunning", false);
        }
        velocity.y += gravity * Time.deltaTime;
```

2023-12-01 13:01 UTC, sneakzttv commented on Assets/Scripts/Player/PlayerController.cs
> +    // Consider moving all Behaviours into seperate script
```suggestion
   #region Dash

IEnumerator DashRoll()
{
    float dashAnimation = Time.time + dashDuration;
    float dashComplete = dashAnimation + dashCooldown;
    float dashedSpeed = moveSpeed * dashSpeedModifier;
    
    while (Time.time < dashComplete)
    {
        // This includes the cool down in the while loop, but only updates the movement during the intended animation sequence 
        if (Time.time < dashAnimation)
        {
            controller.Move(transform.rotation * currentMovement * (dashedSpeed * Time.deltaTime));
        }
        yield return null;
    }

    isDodgeRolling = false;
}

#endregion
```

2023-12-01 13:20 UTC, RyRy79261 commented on Assets/Scripts/Player/PlayerController.cs
> +    // Consider moving all Behaviours into seperate script
Lol, `transform.rotation` I feel like I'm in CSS again 😂 

Thanks!

2023-12-04 08:51 UTC, kantagara requested changes
There are couple of things that should be sorted out:

1. Increase Dash Speed Modifier to something like 5 or 6
2. Remove the boolean isDodgeRolling, introduce a new field of type Coroutine called dashRollCoroutine.  Because currently the coroutines were being called repeatedly, and that shouldn't be an indented behavior.
3. ```/// <summary>
    /// Used for player dodge rolling input
    /// </summary>
    private void OnDodgeRollInput(InputAction.CallbackContext context)
    {
        if (dashRollCoroutine == null)
            dashRollCoroutine = StartCoroutine(DashRoll());
    }``` the OnDodgeRollInput method should look like this
4. Make a unified naming, is it dodge roll or dash roll (I would say Dash Roll)
5. ```IEnumerator DashRoll()
    {
        float dashAnimation = Time.time + dashDuration;
        float dashComplete = dashAnimation + dashCooldown;
        float dashedSpeed = moveSpeed * dashSpeedModifier;
    
        while (Time.time < dashComplete)
        {
            // This includes the cool down in the while loop, but only updates the movement during the intended animation sequence 
            if (Time.time < dashAnimation)
            {
                controller.Move(transform.rotation * currentMovement * (dashedSpeed * Time.deltaTime));
            }
            yield return null;
        }
        dashRollCoroutine = null;
    }``` dashRoll Coroutine should look like this. 
6. Remove DodgeRoll method from Update();

Later on we'll most likely  move towards the state machine implementation, but for now I think this would be enough.

2023-12-04 15:28 UTC, sneakzttv approved these changes

2023-12-04 15:36 UTC, merged